### PR TITLE
Update README with video presentation link and live version link

### PR DESCRIPTION
**Pull request by SergSkol**
-Add preview to README
-Add link to video presentation
-Add link to Live version (Render)

### CODE REVIEW

**Comment by addod19** [comment]
### Hi @SergSkol, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because linters have not been set up correctly for this repository.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by t-yanick — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED

Hi @SergSkol , 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Video within the 5 minutes recommended duration. Great presentation. I am proud of the code you find interesting
:heavy_check_mark: All pages present and functionality as expected.
:heavy_check_mark: Postgres used for database and devise for authentication.
:heavy_check_mark: Database schema reflects given structure.
:heavy_check_mark: Tests all passing
:heavy_check_mark: Model associations all setup correctly.

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
I will request changes here because your files are not displaying in the **Files changed**

- [ ] In your `_payment.html.erb` file, there is a commented line of code on `line 9`. Kindly remove it
- [ ] When I run your app on the [live version](https://budget-app-ror-szss.onrender.com/users/sign_up) I am unable to SIGNUP. I think your deployment with Render is unable to migrate your database. You can consider using Netlify or Githup pages if you keep having issues with Render

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Making your PR more descriptive

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by t-yanick — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED

Hi @SergSkol , 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Video within the 5 minutes recommended duration. Great presentation. I am proud of the code you find interesting
:heavy_check_mark: All pages present and functionality as expected.
:heavy_check_mark: Postgres used for database and devise for authentication.
:heavy_check_mark: Database schema reflects given structure.
:heavy_check_mark: Tests all passing
:heavy_check_mark: Model associations all setup correctly.

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
I will request changes here because your files are not displaying in the **Files changed**

- [ ] In your `_payment.html.erb` file, there is a commented line of code on `line 9`. Kindly remove it
- [ ] When I run your app on the [live version](https://budget-app-ror-szss.onrender.com/users/sign_up) I am unable to SIGNUP. I think your deployment with Render is unable to migrate your database. You can consider using Netlify or Githup pages if you keep having issues with Render

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Making your PR more descriptive

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by julie-ify — APPROVED** [review]
Hi @SergSkol,

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
